# -*- coding: utf-8 -*-
"""class1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ffBhkcKY3fkV1ojrLoYxiM_uCF-FwxpA
"""

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
  if x == "banana":
    break

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
  if x == "banana":
    continue

for x in "banana":
  print(x)

def fuction_m(a,b):
  print(a+b)

fuction_m(1,2)

import matplotlib.pyplot as plt
from scipy import stats
x = [5,7,8,7,2,17,2,9,4,11,12,9,6]
y = [99,86,87,88,111,86,103,87,94,78,77,85,86]
slope,intercept,r,p,str_err=stats.linregress(x,y)
def myfunc(x):
  return slope * x + intercept
mymodel=list(map(myfunc,x))
plt.scatter(x,y)
plt.plot(x,mymodel)#to remove the line
plt.show()

from scipy import stats
x = [5,7,8,7,2,17,2,9,4,11,12,9,6]
y = [99,86,87,88,111,86,103,87,94,78,77,85,86]
slope,intercept,r,p,str_err=stats.linregress(x,y)
def myfunc(x):
  return slope * x + intercept
speed=myfunc(10)
print(speed)